### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by sourabh-spadaki** [BhargavaRavaliKoganti/Online_Auction_System_Project#1]
I'm getting these errors 

C:\Python27\python.exe "C:/Users/Sourabh Padaki/Desktop/Online_Auction_System_Project-master/manage.py"
Traceback (most recent call last):
  File "C:/Users/Sourabh Padaki/Desktop/Online_Auction_System_Project-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 55, in __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Sourabh Padaki\Desktop\Online_Auction_System_Project-master\online_auction_system\settings.py", line 166, in <module>
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'AWS_ACCESS_KEY_ID'

**Comment by BhargavaRavaliKoganti** [comment]
Just remove the aws access key id in settings.py file. I added for deploying, you remove it and try to run.
